### ISSUE TITLE
'data-order-id' option is not working

### ISSUE THREAD

**Issue by juddbaguio** [paypal/react-paypal-js#137]
### 🐞 Describe the Bug

PayPalButton redirects me to the default order page which costs '.01' instead of the right amount created from server-side.

### 🔬 Minimal Reproduction

Just set 'data-order-id' on the PayPalScriptProvider

### 😕 Actual Behavior

Sent me the default checkout page which costs '.01

### 🤔 Expected Behavior

Should asked for "right" amount instead of '0.01'.

### 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | latest
| Browser          | Chrome
| Operating System | Windows

**Comment by gregjopa** [comment]
Hi @juddbaguio can you share a code example?

Ideally this should work since with accept `data-order-id` as a data attribute for integrations creating the order on the server-side: https://developer.paypal.com/docs/checkout/reference/customize-sdk/#order-id.

Note that you also need to return this same order id in your `createOrder()` callback. Otherwise it won't use it and it will make the default v2 orders call that is $0.01 amount.
