### ISSUE TITLE
[Feature] Dynamic amount without re-rendering

### ISSUE THREAD

**Issue by bugatti12345** [paypal/react-paypal-js#161]
### 🚀 Feature Proposal

Based on my knowledge, this SDK only support dynamic amount with `forceReRender`. However, it result as the `Paypal button` disappear and show again within 1 sec if the amount input section and Paypal button are on the same page. It will be nice if we can pass an dynamic amount whenever `createOrder` is called rather than store the initial value when button rendering.

### Motivation

My idea is to take an `amount props` in and return out when calling `createOrder`

### Example

```
    const handleCreateOrder = (data, actions) => {
        return actions.order.create({
            purchase_units: [
                { amount: { value: data.amount} }
            ]
        })
    }
    return (
        <PayPalButtons
            amount={amount}
            createOrder={(data, actions) => handleCreateOrder(data, actions)}
        />
    )
```
or pass the dynamic amount props in when initiating Paypal context
```
    const paypalOptions = {
        "client-id": paypalClientId,
        currency: "CAD",
        amount: amount  //dynamic amount from state
    }
    return (
        <PayPalScriptProvider options={paypalOptions}>
            <PayPalButtons />
        </PayPalScriptProvider>
    )
```

**Comment by gregjopa** [comment]
Hi @bugatti12345, currently react-paypal-js tries to provide a very thin layer of abstraction on top of the PayPal JS SDK interface. We are very cautious about adding new props that don't already exist in the `window.paypal.Buttons()` public interface. Also, there are many other arguments to the v2/orders api besides `amount` so we need to be considerate of that as well: https://developer.paypal.com/docs/api/orders/v2/. Because of that, I do not want to add `amount` as a new prop.

I do think Preston's recommended answer of using a class component or `useRef` is the best approach: https://stackoverflow.com/a/69265765. Were you able to implement that on your end? I'm going to close this out for now. Feel free to re-open if you are still having trouble.

**Comment by HasanMothaffar** [comment]
I also ran into this issue in an app I'm working on, and I agree that the current re-rendering mechanism with the `forceRerender` prop is not user friendly. I managed to solve this issue using `useRef`, as suggested in the solution that @gregjopa provided. Thank you!
