### ISSUE TITLE
[BUG]: Using the sandbox tokenized key supplied by braintree causes the BraintreePaypalButtons to fail to render

### ISSUE THREAD

**Issue by 9nick9** [paypal/react-paypal-js#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I am attempting to build the BraintreePayPalButtons but I get an error if I use the sandbox tokenized key from braintree as opposed to the client token.  Other members of my team are working on the server side to get the tokens generating so I wanted to use the static key while this was in progress. 

Code I am using:
```
const braintreeToken = 'sandbox_random_bt_string';
  const paypalToken =
    'test';

  return (
    <div>
      <PayPalScriptProvider
        options={{
          'client-id': paypalToken,
          components: 'buttons',
          'data-client-token': braintreeToken,
          intent: 'tokenize',
          vault: true,
          currency: 'USD',
        }}
      >
        <BraintreePayPalButtons
          disabled={false}
          fundingSource="paypal" // Available values are: ["paypal", "card", "credit", "paylater", "venmo"]
          createBillingAgreement={createBillingAgreement}
          onApprove={onApprove}
        />
      </PayPalScriptProvider>
    </div>
  );
```

### 😕 Current Behavior

Paypal button fails to render and I get the following error message:

Failed to render <PayPalButtons /> component. Failed to initialize:  InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
in PayPalButtons (created by BraintreePayPalButtons

### 🤔 Expected Behavior

Paypal button renders correctly

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by borodovisin** [comment]
Hi @9nick9, checking the code snippet you post above, you are facing a rendering problem because the key "data-client-token" is not a real JWT token 😢. To use the Braintree you should use a real JWT token 🔒, not a random string ✍️.

Please check out this URL: `https://paypal.github.io/react-paypal-js/?path=/docs/braintree-braintreepaypalbuttons--billing-agreement`. There we have a good example of what you are trying to accomplish. 

In the example code, we're calling this endpoint: `https://braintree-sdk-demo.herokuapp.com/api/braintree/auth` to get a new fresh JWT token and set it in the key `data-client-token`.

You can use that token for testing purposes in the sandbox environment. 

I hope this can be helpful 👍. Feel free to play around with our doc page samples, which can be a good source of knowledge since we're updating those pages often and trying to make it easier for the final user to understand the integration process.

In the case you continue facing the same issue, please let me know and I can dig a little more into the source of the problem.

Otherwise is this comment helps you with your problem please close this issue. 📪

**Comment by 9nick9** [comment]
The issue is that braintree has 2 key types, only 1 of which is a jwt token. The other type, that looks similar to what I passed in, does not work.  If only the client tokens are allowed then having that documented somewhere would be very helpful.

**Comment by 9nick9** [comment]
The Braintree documention for that key is located here https://developer.paypal.com/braintree/docs/guides/authorization/tokenization-key

**Comment by borodovisin** [comment]
Hi, @9nick9 I understand the problem you're facing using the `react-paypal-js` wrapper library with the `tokenization key`.

The BraintreePayPalButtons component was introduced recently and now it's working only with the client token (`JWT`).
That probably it's a gap in our library and in the near future we can support both cases the `client token` and the `tokenization key`.

In the meantime, we are planning to update the `react-paypal-js` documentation to avoid any kind of confusion using the key `data-client-token`.

**Comment by borodovisin** [comment]
Hi @9nick9, I think you can use this key `data-user-id-token` to make it work. That key allows you to use your Braintree tokenizati/on key. 

**The bad news** is in the latest release of the library, we don't support the `data-user-id-token`, this is an issue/gap on our end.

Searching in the libraries code we're using two keys `data-client-token` and `data-user-id-token`. The user should use the first one for JWT tokens and the second one for tokenization keys.

The next week we'll release a new version with this change supporting both keys and also improving the documentation, to make it clear how to use both keys

Thanks again for your feedback.

**Comment by 9nick9** [comment]
Thanks. That sounds good to me.

**Comment by borodovisin** [comment]
Hi @9nick9, the tokenization key is supported now on version >=7.5 of the library.
