### ISSUE TITLE
[FEATURE]: Add option to use updated logo

### ISSUE THREAD

**Issue by michaeljamie** [paypal/react-paypal-js#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I wish I had the option to display the updated logo from the [PayPal brand identity guide](https://newsroom.paypal-corp.com/media-resources) in the PayPalButtons component.  I see the logo included in the buttons in the [PayPal Javascript SDK documentation](https://developer.paypal.com/sdk/js/reference/#style), however the addition of the PayPal logo on the buttons would be a great option to include as props for the PayPalButtons Component:

![image](https://github.com/paypal/react-paypal-js/assets/26236137/a02e725e-ba9e-4545-864c-408de0242ac5)

Developers and designers seek to stay on trend with the latest logo available from company brand guides, and allowing for either customization or updating the logo on the PayPal Buttons component would be a great addition to this package.

### Describe the solution you'd like

Ideally we would have props passed to the style object to allow for either this logo:

![image](https://github.com/paypal/react-paypal-js/assets/26236137/7c951ffc-50c2-448a-b67a-7296c53607f2)

Or this logo:

![image](https://github.com/paypal/react-paypal-js/assets/26236137/361ab1ea-1afe-4fb9-96b1-7c76cde18c2f)

### Describe alternatives you've considered

We considered adding the logo manually and placing it on top of the button, however it would be much easier to allow users the ability to decide which PayPal logo to use, especially since the updated logo from the brand guide isn't currently the one that appears on the buttons.  Adding more options would increase the usage of this npm package and allow for more customization on the user side.

**Comment by michaeljamie** [comment]
Bump

**Comment by michaeljamie** [comment]
Bump

**Comment by devchristina** [comment]
Sent this request to product/engineering for advice/solution.

**Comment by devchristina** [comment]
@michaeljamie are you referring to this react component which only has “PayPal” instead of “:pp: PayPal” https://paypal.github.io/react-paypal-js/?path=/docs/example-paypalbuttons--default

**Comment by michaeljamie** [comment]
Thank you @devchristina .  That's correct.  It would be great if we could update those components to use the “:pp: PayPal” icon/logo (possibly as a prop) if possible.  Thanks for looking into this 👍

**Comment by michaeljamie** [comment]
Bump

**Comment by michaeljamie** [comment]
Bump

**Comment by wsbrunson** [comment]
hi @michaeljamie thank you for reaching out!

Our team took a look and turns out those screenshots on the developer docs are from the previous version of the PayPal SDK, v4 or checkout.js. That page has been up for so long and we've never noticed!

Unfortunately there isn't a configurable way to bring those logos to the v5 version of the SDK. We do have a project planned in the near future to do the following:

* update styling of the buttons
* expose more options for styling to merchants
* more configurable labels

We'll bring up adding in logos too or making a configuration option for turning them on.

In the meantime, we are going to update those screenshots on the developer documentation site to match what merchants will actually see when they render the PayPal JS SDK.

Thanks again!
