### ISSUE TITLE
Logging out of Paypal Session

### ISSUE THREAD

**Issue by AlexanderKapitsa** [paypal/react-paypal-js#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Hello!

I have checked documentation here [https://developer.paypal.com/sdk/js/reference/](https://developer.paypal.com/sdk/js/reference/) and other places (StackOverflow, ChatGPT) and was not able to find how to logout user programmatically.

The situation is the same as described in the ticket [https://github.com/paypal/paypalcheckout-ios/issues/110](https://github.com/paypal/paypalcheckout-ios/issues/110) .
As described in mentioned issue, there is possibility that newly logged in application user may reuse PayPal session created by previous application user.

As I can see logging out functionality is already added to ios and android sdk:
[https://github.com/paypal/paypalcheckout-ios/issues/110](https://github.com/paypal/paypalcheckout-ios/issues/110)
[https://github.com/paypal/android-checkout-sdk/issues/99](https://github.com/paypal/android-checkout-sdk/issues/99)

Is there something similar in react-paypal-js or paypal-js?

**Comment by monti-star** [comment]
Hi @AlexanderKapitsa

I'll check with the engineering team on this and get you an answer. Alternatively, I'll take this feedback about the information not being found in our documentation to be fixed once we have the answer.

**Comment by gregjopa** [comment]
Hi @AlexanderKapitsa, are you concerned with different paypal buyers sharing the same web browser? Just trying to understand the problem you are running into. On the web, we use secure cookies to remember the user's logged in state. Those are not shared across devices.

**Comment by AlexanderKapitsa** [comment]
Hello, @gregjopa, yes I'm concerning that one web browser may be used by different users.
So for us it is safer to log out paypal session each time one user finalizes payment.

**Comment by devchristina** [comment]
Hi @AlexanderKapitsa -- we'll need to work with our web team to understand the difference between the mobile vs web integrations to know if this is use case is even achievable. Hope to get you an answer asap.

**Comment by AlexanderKapitsa** [comment]
@devchristina , thanks a lot!

**Comment by devchristina** [comment]
Hi @AlexanderKapitsa, we've asked around and were provided the following information about the web experience: 

This functionality is not available because the lifecycle of authentication occurs outside of the SDK (on the [paypal.com](http://paypal.com/) domain) - A similar situation would be:

- user logs into [paypal.com](http://paypal.com/) for some other reason
- user visits merchant's site and starts checkout
- user is not prompted to log in because they already have an active auth session on [paypal.com](http://paypal.com/)

Due to this, I will close this issue as will not fix since there is not plans to change this functionality. If you'd like to re-open because of concerns, please feel free to do so.

**Comment by AlexanderKapitsa** [comment]
Hello @devchristina!

That is interesting. 
So in case if user will log out from paypal on one browser page that will affect cookies of paypal.com domain and that automatically will log out on other pages.
Or something like that.

Ok, thanks for response. Will try to solve our issue in other manner.
