### ISSUE TITLE
Weird implementation of `usePayPalScriptReducer`

### ISSUE THREAD

**Issue by pedroapfilho** [paypal/react-paypal-js#59]
So, if I want to just dispatch actions, without touching the `state`, I have to:

```
  const [, paypalDispatch] = usePayPalScriptReducer();
```

What is very ugly, and looks like a workaround, but actually it's the only way of doing it without bugging my linter.

What if we implement it as an object? So we can have the `dispatch` and the `state` inside the `paypal` object that we render using `usePayPal`? It would be much nicer to use, like:

```
const paypal = usePayPal

paypal.dispatch({
      type: "resetOptions",
      value: {
        currency: selectedCurrency,
      },
    })
```

And it would be nice to not have to pass the `paypalScriptOptions` every time we dispatch an action, as it would be available on the `Provider` already.

**Comment by gregjopa** [comment]
>   const [, paypalDispatch] = usePayPalScriptReducer();
What is very ugly, and looks like a workaround, but actually it's the only way of doing it without bugging my linter.

This `[state, dispatcher]` design is modeled after [React's useReducer hook](https://reactjs.org/docs/hooks-reference.html#usereducer) and is pretty common. I know the syntax isn't the prettiest, but you get use to it after a while.

> it would be nice to not have to pass the paypalScriptOptions every time we dispatch an action, as it would be available on the Provider already.

We are open to PRs to add a new `updateOptions` action for the dispatcher. I think if you look back in git history we originally had it that way. We went with `resetOptions` since there are use cases when you want to remove a query param (like when switching from Orders to Subscriptions) and the `updateOptions` approach wouldn't work well for removing existing keys. I'm cool with having two different actions (`resetOptions` and `updateOptions`) so it's up to the implementer to choose.

**Comment by pedroapfilho** [comment]
Hey @gregjopa thanks again for the quick response, you're great!

I think that it's ok with the current implementation, it's just a matter of discussion of how to architecture the `hooks`, but you've got a point.

About the use cases, I had it in the past, but I think that after knowing that this was to make it more resilient for other use cases, that's fine, we should keep the package as `non-opinionated` as possible.

Thanks again!
