### ISSUE TITLE
[Bug] Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by bhavikagrawal** [paypal/react-paypal-js#92]
### 🐞 Describe the Bug

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided does not match the recipient window's origin ('https://www.sandbox.paypal.com').

Same is working on localhost.

### 🔬 Minimal Reproduction

1) add product to cart
2) add to cart and go to cart page
3) Paypal button is not loading correctly. Errors logged in console.

### 😕 Actual Behavior

PayPal script not working on our website but works on localhost

### 🤔 Expected Behavior

It should load correctly

### 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 4.1.1
| Browser          | chrome Version 89.0.4389.82 
| Operating System | Windows 7

**Comment by gregjopa** [comment]
Hi @bhavikagrawal it's great to hear you are using react-paypal-js! 

I took a look at your [dev site](https://www-development.aws.searspartsdirect.com/) and noticed your web server is setting the http response header `X-Frame-Options: SAMEORIGIN`. I think this header will block the paypal button from working since we depend on being able to serve up code from www.paypal.com/www.sandbox.paypal.com using iframes. 

Can you try removing this header to see if it fixes the problem?

**Comment by bhavikagrawal** [comment]
@gregjopa Can you please delete the issue permanently from repository. Or remove the hyperlink to our dev site.

**Comment by RishikeshDarandale** [comment]
@gregjopa, a basic question here: Why paypal wants to `iFrame` client application? I think, it should be the other way. correct?

**Comment by gregjopa** [comment]
Hi @bhavikagrawal, I removed the hyperlink to your dev site.

@RishikeshDarandale we use iframes for a number of reasons. It's a guaranteed way to sandbox our 3rd party code. The PayPal JS SDK use [Zoid](https://github.com/krakenjs/zoid) for managing the iframe abstraction with components and this react library is just making it easier to use the JS SDK in react land. You can read more about the benefits of iframes here: https://bluepnume.medium.com/introducing-xcomponent-seamless-cross-domain-web-components-from-paypal-c0144f3e82bf

**Comment by bhavikagrawal** [comment]
@gregjopa I have tried removing the header, but it did not worked.

When i disabled `adobedtm` script from running on website, it started working. What could be a possible conflict because of other external script.

**Comment by gregjopa** [comment]
Hi @bhavikagrawal, I'm not sure why Adobe DTM is conflicting with the PayPal JS SDK. Adobe DTM typically loads a bunch of 3rd party tags on websites so it could be one of those 3rd party scripts that's conflicting. I doubt this issue is related to this react library. Can you try creating a minimal reproduction that does not use React and instead uses the PayPal JS SDK and Adobe DTM directly? Please create an issue over in the paypal-checkout-components repo with the minimal reproduction and then the sdk team can take a look: https://github.com/paypal/paypal-checkout-components/issues
